name: Deploy Mustard Seed Radio

on:
  push:
    branches:
      - main
      - develop
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build site
        run: |
          mkdir build
          rsync -av --exclude build . build

      - name: Set domain
        if: github.event_name == 'push'
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "mustardseed.gr" > build/CNAME
          elif [ "${{ github.ref_name }}" = "dev" ]; then
            echo "dev.mustardseed.gr" > build/CNAME
          fi

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4